function [fitresult, gof] = Gauss3(M, Open)
%CREATEFIT(M,OPEN)
%  Create a fit.
%
%  Data for 'SH600677' fit:
%      X Input : M
%      Y Output: Open
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jan-2017 15:36:14


%% Fit: 'SH600677'.
[xData, yData] = prepareCurveData( M, Open );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [21.8 92 18.048072036116 20.4397615998153 31 8.87344025921902 18.5595303475873 2 19.6190999738226];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'SH600677' );
% h = plot( fitresult, xData, yData );
% legend( h, 'Open vs. M', 'SH600677', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'M' );
% ylabel( 'Open' );
% grid on


